# ~/.config/starship.toml

format = """
$hostname$directory$git_branch$git_status$rust$c$cmake$cpp$kotlin$maven$meson$php$python$nodejs$java$lua$cmd_duration
$jobs$character"""

right_format = """
$status$time
"""

add_newline = true
command_timeout = 1200

palette = "custom"

[palettes.custom]
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
yellow = "#e0af68"
red = "#f7768e"
purple = "#bb9af7"
fg = "#c0caf5"
muted = "#565f89"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold yellow)"

[directory]
style = "bold blue"
read_only = "[-]"
read_only_style = "red"
truncation_length = 4
truncate_to_repo = true
home_symbol = "~"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
style = "purple"
format = "[$symbol$branch]($style) "

# [git_status]
# style = "yellow"
# format = "([$all_status$ahead_behind]($style) )"
# conflicted = "="
# ahead = "⇡${count}"
# behind = "⇣${count}"
# diverged = "⇕⇡${ahead_count}⇣${behind_count}"
# up_to_date = ""
# untracked = "?${count}"
# stashed = "$"
# modified = "!${count}"
# staged = "+${count}"
# renamed = "»${count}"
# deleted = "x${count}"

[python]
symbol = "python "
style = "cyan"
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
detect_extensions = ["py"]
detect_files = ["pyproject.toml", "requirements.txt", "setup.py", "tox.ini"]

[nodejs]
symbol = "node "
style = "green"
format = "[$symbol$version]($style) "
detect_extensions = ["js", "mjs", "cjs", "ts", "tsx"]
detect_files = ["package.json"]

[java]
symbol = "java "
style = "red"
format = '[${symbol}(${version} )]($style)'
detect_extensions = ["java", "class", "jar", "gradle", "clj", "cljc"]
detect_files = ["pom.xml", "build.gradle", "build.gradle.kts", ".java-version"]

[lua]
symbol = "lua"
format = "[$symbol]($style) "

[cmd_duration]
min_time = 1000
style = "yellow"
format = "[took $duration]($style) "

[status]
disabled = false
style = "red"
format = "[exit $status]($style) "

[time]
disabled = false
time_format = "%H:%M"
style = "muted"
format = "[$time]($style)"

[hostname]
ssh_only = true
style = "bold green"
ssh_symbol = ""
format = "[$ssh_symbol - $hostname]($style) "

[username]
disabled = true

[package]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[kubernetes]
disabled = true

[docker_context]
disabled = true

[rust]
disabled = false
symbol = "rust "
format = "[$symbol]($style)"

[golang]
disabled = true

[php]
disabled = true

[ruby]
disabled = true

[c]
disabled = false
symbol = "C "
format = "[$symbol]($style)"

[maven]
disabled = false
symbol = "mvn "
format = "[$symbol]($style)"
